export const SITE = {
  name: "JULEHOME",
  legalName: "JULEHOME",
  description:
    "Velas aromáticas, difusores y decoración elegante para crear hogares llenos de calidez, paz y bienestar. Ilumina tu hogar con elegancia.",
  url: "https://julehome.com",
  slogan: "Ilumina tu hogar con elegancia.",
  email: "hola@julehome.com",
  phone: "+57 317 620 2258",
  whatsapp: "573176202258",
  instagram: "https://instagram.com/julehome",
  pinterest: "https://pinterest.com/julehome",
  tiktok: "https://tiktok.com/@julehome",
  facebook: "https://facebook.com/julehome",
  shippingCost: 25000,
  freeShippingFrom: 250000,
  currency: "COP",
  address: "Calle 45 # 26-24, Cabecera del Llano, Bucaramanga, Santander, Colombia",
  hours: "Lun – Vie · 7:00 – 18:00",
} as const;

export const CIUDADES_COLOMBIA = [
  "Apartadó",
  "Armenia",
  "Arauca",
  "Barrancabermeja",
  "Barranquilla",
  "Bello",
  "Bogotá D.C.",
  "Bucaramanga",
  "Buenaventura",
  "Buga",
  "Cali",
  "Cartagena",
  "Chía",
  "Ciénaga",
  "Cota",
  "Cúcuta",
  "Dosquebradas",
  "Duitama",
  "Envigado",
  "Espinal",
  "Florencia",
  "Floridablanca",
  "Fusagasugá",
  "Girardot",
  "Girón",
  "Ibagué",
  "Inírida",
  "Ipiales",
  "Itagüí",
  "Leticia",
  "Magangué",
  "Maicao",
  "Malambo",
  "Manizales",
  "Medellín",
  "Mitú",
  "Mocoa",
  "Montería",
  "Neiva",
  "Ocaña",
  "Palmira",
  "Pasto",
  "Pereira",
  "Piedecuesta",
  "Popayán",
  "Puerto Carreño",
  "Quibdó",
  "Riohacha",
  "Rionegro",
  "San Andrés",
  "San José del Guaviare",
  "Santa Marta",
  "Santa Rosa de Cabal",
  "Sincelejo",
  "Soacha",
  "Sogamoso",
  "Soledad",
  "Tuluá",
  "Tumaco",
  "Tunja",
  "Valledupar",
  "Villavicencio",
  "Yopal",
  "Yumbo",
  "Zipaquirá",
] as const;

export const NAV_LINKS = [
  { label: "Inicio", href: "/" },
  { label: "Tienda", href: "/tienda" },
  { label: "Colecciones", href: "/colecciones" },
  { label: "Navidad", href: "/colecciones/navidad" },
  { label: "Nosotros", href: "/nosotros" },
  { label: "Contacto", href: "/contacto" },
] as const;

export const FOOTER_LINKS = {
  tienda: [
    { label: "Todas las velas", href: "/tienda" },
    { label: "Decoración", href: "/tienda?categoria=decoracion" },
    { label: "Colección Navidad", href: "/colecciones/navidad" },
  ],
  empresa: [
    { label: "Nosotros", href: "/nosotros" },
    { label: "Colecciones", href: "/colecciones" },
    { label: "Contacto", href: "/contacto" },
    { label: "Preguntas frecuentes", href: "/preguntas-frecuentes" },
  ],
  legal: [
    { label: "Política de privacidad", href: "/politicas?seccion=privacidad" },
    { label: "Política de cookies", href: "/politicas?seccion=cookies" },
    { label: "Términos y condiciones", href: "/politicas?seccion=terminos" },
    { label: "Envíos", href: "/politicas?seccion=envios" },
  ],
} as const;
